# action.yml
name: 'Update Release Metadata'
description: 'Update the release metadata JSON for an ECS service.'
inputs:
  aws-region:
    description: 'AWS region.'
    required: true
    default: us-east-1
  ecs-cluster:
    description: 'ECS Cluster'
    required: true
  ecs-service:
    description: 'ECS Service'
    required: true
  metadata-bucket:
    description: 'Metadata bucket'
    required: true
  metadata-key:
    description: 'Metadata key'
    required: true
  release-tag:
    description: 'Release tag'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_REGION: ${{ inputs.aws-region }}
    ECS_CLUSTER: ${{ inputs.ecs-cluster }}
    ECS_SERVICE: ${{ inputs.ecs-service }}
    METADATA_BUCKET: ${{ inputs.metadata-bucket }}
    METADATA_KEY: ${{ inputs.metadata-key }}
    RELEASE_TAG: $${{ inputs.release-tag }}
